import './globals.css'

import type { Metadata } from 'next'
// Importa fontes gratuitas do google
import { Montserrat, Oxanium } from 'next/font/google'

export const metadata: Metadata = {
  title: 'DevStage',
  description: 'Generated by create next app',
}

// Cria uma configuração para a font Oxanium e armazena em uma variável "--font-oxanium"
const oxanium = Oxanium({
  weight: ['500', '600'],
  subsets: ['latin'],
  variable: '--font-oxanium',
})

// Cria uma configuração para a font Montserrat e armazena em uma variável "--font-montserrat"
const montserrat = Montserrat({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    // Adiciona as duas fontes ao documento html
    <html lang="en" className={`${oxanium.variable} ${montserrat.variable}`}>
      <body className="bg-gray-900 text-gray-100 antialiased bg-[url(/background.png)] bg-no-repeat bg-top sm:bg-right-top">
        {children}
      </body>
    </html>
  )
}
